import type { CardImage } from '../types/game'

/** Unique card faces — each appears exactly twice on the board (up to 25 pairs) */
export const CARD_IMAGES: CardImage[] = [
  { id: 'star', label: 'Star', emoji: '⭐', gradient: 'from-amber-400 to-orange-600' },
  { id: 'moon', label: 'Moon', emoji: '🌙', gradient: 'from-indigo-400 to-violet-700' },
  { id: 'fire', label: 'Fire', emoji: '🔥', gradient: 'from-red-400 to-rose-600' },
  { id: 'leaf', label: 'Leaf', emoji: '🍃', gradient: 'from-emerald-400 to-green-700' },
  { id: 'gem', label: 'Gem', emoji: '💎', gradient: 'from-cyan-400 to-blue-600' },
  { id: 'bolt', label: 'Bolt', emoji: '⚡', gradient: 'from-yellow-300 to-amber-500' },
  { id: 'heart', label: 'Heart', emoji: '💖', gradient: 'from-pink-400 to-fuchsia-600' },
  { id: 'rocket', label: 'Rocket', emoji: '🚀', gradient: 'from-sky-400 to-indigo-600' },
  { id: 'sun', label: 'Sun', emoji: '☀️', gradient: 'from-yellow-400 to-orange-500' },
  { id: 'snow', label: 'Snow', emoji: '❄️', gradient: 'from-sky-200 to-blue-500' },
  { id: 'cat', label: 'Cat', emoji: '🐱', gradient: 'from-orange-300 to-amber-600' },
  { id: 'dog', label: 'Dog', emoji: '🐶', gradient: 'from-amber-300 to-yellow-700' },
  { id: 'fish', label: 'Fish', emoji: '🐠', gradient: 'from-teal-300 to-cyan-600' },
  { id: 'tree', label: 'Tree', emoji: '🌳', gradient: 'from-green-400 to-emerald-700' },
  { id: 'cake', label: 'Cake', emoji: '🎂', gradient: 'from-pink-300 to-rose-500' },
  { id: 'music', label: 'Music', emoji: '🎵', gradient: 'from-purple-400 to-violet-600' },
  { id: 'ball', label: 'Ball', emoji: '⚽', gradient: 'from-lime-400 to-green-600' },
  { id: 'key', label: 'Key', emoji: '🔑', gradient: 'from-yellow-500 to-amber-700' },
  { id: 'bell', label: 'Bell', emoji: '🔔', gradient: 'from-amber-200 to-yellow-600' },
  { id: 'book', label: 'Book', emoji: '📚', gradient: 'from-blue-400 to-indigo-600' },
  { id: 'rainbow', label: 'Rainbow', emoji: '🌈', gradient: 'from-pink-400 via-purple-400 to-blue-500' },
  { id: 'ghost', label: 'Ghost', emoji: '👻', gradient: 'from-slate-300 to-slate-500' },
  { id: 'pizza', label: 'Pizza', emoji: '🍕', gradient: 'from-red-300 to-orange-500' },
  { id: 'crown', label: 'Crown', emoji: '👑', gradient: 'from-yellow-400 to-amber-600' },
  { id: 'flower', label: 'Flower', emoji: '🌸', gradient: 'from-pink-300 to-rose-500' },
]
